#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

/sbin/swapoff -a

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

set clobber
/bin/mkdir -p /boot/files
/usr/bin/touch /boot/files/networks_list.txt
/usr/bin/python /home/pi/Documents/workspace/papermirror/generate_wpa_conf.py  /boot/files/networks_list.txt /etc/wpa_supplicant/wpa_supplicant.conf

cd /home/pi/Documents/workspace/papermirror;nohup python continuous_camera.py > /var/log/continuous_camera.log 2>&1 &
exit 0
